workaround for Firefox 32 "cross-origin object" bug
On Firefox 32 getting a location fails with error:
System JS : ERROR resource://gre/modules/addons/XPIProvider.jsm ->
jar:file:///tmp/tmpW3LbhK.mozrunner/extensions/jid1-HdwPLukcGQeOSh@jetpack.xpi!/bootstrap.js
-> resource://gre/modules/commonjs/toolkit/loader.js ->
resource://gre/modules/commonjs/sdk/loader/sandbox.js ->
resource://jid1-hdwplukcgqeosh-at-jetpack/location-guard/data/js/content.js:35 -
Error: Not allowed to define cross-origin object as property on [Object] or
[Array] XrayWrapper.

This is caused by modifying data.args in content.js, we clone it as a
workaround.